CC = gcc

RAYLIB_FLAGS = -I/opt/homebrew/include -L/opt/homebrew/lib -lraylib \
-framework OpenGL -framework Cocoa -framework IOKit -framework CoreVideo

COMMON_SRC = graph.c file_reader.c dijkstra.c

milestone1:
	$(CC) main_dijkstra.c $(COMMON_SRC) -o dijkstra

milestone2:
	$(CC) main_static.c $(COMMON_SRC) -o sim $(RAYLIB_FLAGS)

milestone3:
	$(CC) main_sim.c $(COMMON_SRC) -o sim $(RAYLIB_FLAGS)

milestone4:
	$(CC) main_m4.c $(COMMON_SRC) traveler.c gui.c -o sim $(RAYLIB_FLAGS)

clean:
	rm -f dijkstra sim